### ISSUE TITLE
Bring back prune?

### ISSUE THREAD

**Issue by bergstand** [Illumina/akt#27]
In earlier versions of akt, the "prune" subcommand provided a nice way to prune/thin variants on the basis of linkage disequilibrium. However, the command has been deprecated and is no longer available in akt.

My understanding is that you favour using a pre-pruned set of human variants that you provide in a VCF. However, this has several limitations: most profoundly, it's of course completely inapplicable to non-human organisms - people do work in plants, yeast, dogs, cattle, flies, basically anything with DNA! But even for human data on the right reference build, the set of provided sites will come with some complex ascertainment bias, might not be optimal when working in more diverse populations with ancestry poorly represented in the 1000 Genomes dataset, and might not overlap well with all present or future genotyping array sites. The "prune" command also provided the additional flexibility of choosing the LD cutoff. There might also be additional use cases for LD pruning other than just obtaining a suitable set of SNPs for genome-wide ancestry analyses.

I would therefore like to request bringing back "prune", which I think would make an already great software even greater. Thanks for your work on akt!

**Comment by jaredo** [comment]
Glad you like akt and I agree with all your points about the need for pruning functionality in many cases (as opposed to using pre-defined alleles).

I chose to deprecate a large number of akt subcommands because of the continued improvement of VCF/BCF support in [plink1.9](https://www.cog-genomics.org/plink/1.9/) which makes a lot of akt's functionality redundant. For example, plink1.9 has really nice pruning functionality (much faster than my implementation). Hence I only I retained the akt subcommands that were not available in plink, notably randomized PCA and the [KING estimator](http://people.virginia.edu/~wc9c/KING/) for relatedness. I do see these are both being added to plink2 though!
