### ISSUE TITLE
pca index assertion error

### ISSUE THREAD

**Issue by croct** [Illumina/akt#37]
Any ideas on what could be causing this problem?  I get this error message when I run on all 17 samples, 1 sample, filtered/unfiltered (e.g. for PASS, AC, AN).

./akt.v0.3.2/akt pca -R ./akt.v0.3.2/data/wgs.grch38_chr.vcf.gz $bcf
Input: filtered_4033.bcf
MAF lower bound: 0
Thin: 1 
Number principle components: 20
Reading data...
1 samples
6002/17491 of study markers were in the sites file
akt: Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<float, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = float; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted (core dumped)

**Comment by 23andme-jaredo** [comment]
I think it is because you are trying to calculate more principal components than there are samples.

The (admittedly undocumented) default is to calculate 20 PCs, try setting `--npca 10`. With so few samples you should also set `-a` for an exact solution.

Note, these days I'd probably just recommend (plink2)[https://www.cog-genomics.org/plink/2.0/].

**Comment by jaredo** [comment]
I think it is because you are trying to calculate more principal components than there are samples.

The (admittedly undocumented) default is to calculate 20 PCs, try setting `--npca 10`. With so few samples you should also set `-a` for an exact solution.

Note 1: these days I'd probably just recommend [plink2](https://www.cog-genomics.org/plink/2.0/strat#pca).

Note 2: I don't think PCA is meaningful for a single sample.

**Comment by croct** [comment]
Thanks for the response.  I have run again on my full (17 sample) with --npca 10 as suggested & it works.  I had not thought about the # PC's > # samples issue.
