### ISSUE TITLE
explanation of basic resource requirements?

### ISSUE THREAD

**Issue by chlangley** [Illumina/akt#40]
Hello Jaredo:

Is there a discuss available of resource requirements (memory and threads)?

I see the threads are referred to as compression associated (presumably IO).  

But how might one think about the chromosome and the need to chunk it?

I wonder if the constraints are discuss somewhere?

Cheers,
Chuck

**Comment by chlangley** [comment]
I should add that I am interested the pedphase feature in particular.
__

**Comment by jaredo** [comment]
Hi Chuck,

`akt pedphase` only applies simple Mendel rule based phasing on trios. As such it only needs to keep a single line of the VCF in memory at a time so it should be very lightweight on memory usage (two bytes per genotype plus whatever is in the FORMAT metadata).  The exception is when using phase sets where multiple lines would be buffered....it is kind of hard to know the complexity in that setting since it depends on the extent of read based phasing and sample size (I have never seen it get beyond a few GB when phasing a trio with short read data though).

I hope that helps,

Jared
